
export enum GrupoSanguineo{
    A_POSITIVO = "A_POSITIVO",
    A_NEGATIVO = "A_NEGATIVO",
    B_POSITIVO = "B_POSITIVO",
    B_NEGATIVO = "B_NEGATIVO",
    O_POSITIVO = "O_POSITIVO",
    O_NEGATIVO = "O_NEGATIVO",
    AB_POSITIVO = "AB_POSITIVO",
    AO_POSITIVO = "AO_POSITIVO",
    BO_POSITIVO = "BO_POSITIVO",
	AB_NEGATIVO = "AB_NEGATIVO",
    AO_NEGATIVO = "AO_NEGATIVO",
    BO_NEGATIVO = "BO_NEGATIVO"
}
